const EcoStoryRACList = () => {
    return (
        <>
            <div>
                <img
                    src="https://github.com/TeamProject-Dessert39/dataCenter/blob/master/icon/esg_icon3_01.png?raw=true"
                    alt="esg_icon3_01"
                />
                <img
                    src="https://github.com/TeamProject-Dessert39/dataCenter/blob/master/icon/esg_icon3_02.png?raw=true"
                    alt="esg_icon3_02"
                />
                <img
                    src="https://github.com/TeamProject-Dessert39/dataCenter/blob/master/icon/esg_icon3_03.png?raw=true"
                    alt="esg_icon3_03"
                />
                <img
                    src="https://github.com/TeamProject-Dessert39/dataCenter/blob/master/icon/esg_icon3_04.png?raw=true"
                    alt="esg_icon3_04"
                />
            </div>
            <div>
                <img
                    src="https://github.com/TeamProject-Dessert39/dataCenter/blob/master/icon/esg_icon3_05.png?raw=true"
                    alt="esg_icon3_05"
                />
                <img
                    src="https://github.com/TeamProject-Dessert39/dataCenter/blob/master/icon/esg_icon3_06.png?raw=true"
                    alt="esg_icon3_06"
                />
                <img
                    src="https://github.com/TeamProject-Dessert39/dataCenter/blob/master/icon/esg_icon3_07.png?raw=true"
                    alt="esg_icon3_07"
                />
                <img
                    src="https://github.com/TeamProject-Dessert39/dataCenter/blob/master/icon/esg_icon3_08.png?raw=true"
                    alt="esg_icon3_08"
                />
            </div>
            <div>
                <img
                    src="https://github.com/TeamProject-Dessert39/dataCenter/blob/master/icon/esg_icon3_09.png?raw=true"
                    alt="esg_icon3_09"
                />
                <img
                    src="https://github.com/TeamProject-Dessert39/dataCenter/blob/master/icon/esg_icon3_10.png?raw=true"
                    alt="esg_icon3_10"
                />
                <img
                    src="https://github.com/TeamProject-Dessert39/dataCenter/blob/master/icon/esg_icon3_11.png?raw=true"
                    alt="esg_icon3_11"
                />
            </div>
        </>
    );
};

export default EcoStoryRACList;
